# -*- coding: utf-8 -*-
"""A3 NEW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18z-92UFgGzU-q-fUmoV1AhDuwREDmdlZ

1.1 Objective

The required Python libraries are imported to support the development of the NLP sentiment analysis model. These libraries enable data handling, text preprocessing, feature extraction, model training, and performance evaluation.

1.2 Purpose of Libraries
*   Manage and organise data using NumPy and Pandas
*   Process and clean review text using NLTK (tokenisation, stopword removal, lemmatisation)
*  Handle file operations and dataset extraction using os and tarfile
*  Convert text into numerical features using TF-IDF vectorisation
*  Split the dataset into training and testing sets
*   Build a sentiment classification model using Logistic Regression
*   Evaluate model performance using accuracy, confusion matrix, and classification report
"""

# ===============================
# MOUNT GOOGLE DRIVE
# ===============================

from google.colab import drive
drive.mount('/content/drive')   # Connect Google Drive to Colab


# ===============================
# EXTRACT DATASET
# ===============================

import tarfile
import os

# Path of the dataset stored in Google Drive
tar_path = '/content/drive/MyDrive/A3 Sonam & Tshering/domain_sentiment_data.tar.gz'

# Open and extract the compressed dataset
tar = tarfile.open(tar_path)
tar.extractall('/content')      # Extract dataset into Colab
tar.close()

# Check whether the dataset has been extracted successfully
print("Main folder:", os.listdir('/content'))
print("Dataset folders:", os.listdir('/content/sorted_data_acl'))

"""1.3 Mount Google Drive and Extract Dataset

The Google Drive is connected to the Colab environment to access the uploaded sentiment analysis dataset. The dataset is stored as a compressed .tar.gz file and is extracted into the working directory for further processing.
"""

# ===============================
# CONNECT GOOGLE DRIVE
# ===============================

from google.colab import drive
drive.mount('/content/drive')   # Connect Google Drive to Colab


# ===============================
# EXTRACT DATASET
# ===============================

# Define the path to the dataset stored in Google Drive
tar_path = '/content/drive/MyDrive/A3 Sonam & Tshering/domain_sentiment_data.tar.gz'

# Open the compressed (.tar.gz) dataset file
tar = tarfile.open(tar_path)

# Extract all files into the Colab working directory (/content)
tar.extractall('/content')

# Close the file after extraction
tar.close()


# ===============================
# CHECK DATASET
# ===============================

# Display all files and folders in the main directory
print("Main folder:", os.listdir('/content'))

# Display dataset categories (e.g., books, dvd, electronics, kitchen)
print("Dataset folders:", os.listdir('/content/sorted_data_acl'))

"""1.4 Verify dataset extraction by checking if 'sorted_data_acl' folder exists"""

if os.path.exists('/content/sorted_data_acl'):
    print("Dataset extracted successfully")
else:
    print("Extraction failed")

"""1.5 Loading Positive and Negative Reviews

The extracted dataset contains customer reviews categorised into positive and negative sentiments. In this step, the review files are read from the dataset directory and processed to extract the review text. Each review is then labelled as either “positive” or “negative” and stored in a structured format for further analysis.
"""

# ===============================
# LOAD POSITIVE AND NEGATIVE REVIEWS
# ===============================

# Function to read review files and extract review text
def load_reviews(file_path, label):
    reviews = []

    # Open the review file
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
        soup = BeautifulSoup(file.read(), 'html.parser')

    # Find all review text sections
    review_texts = soup.find_all('review_text')

    # Store each review with its label
    for review in review_texts:
        text = review.get_text().strip()
        reviews.append([text, label])

    return reviews


# ===============================
# CHOOSE ONE DATASET CATEGORY
# ===============================

# Example: using books category
category = 'books'

positive_path = f'/content/sorted_data_acl/{category}/positive.review'
negative_path = f'/content/sorted_data_acl/{category}/negative.review'


# Load positive and negative reviews
positive_reviews = load_reviews(positive_path, 'positive')
negative_reviews = load_reviews(negative_path, 'negative')


# Combine both positive and negative reviews
all_reviews = positive_reviews + negative_reviews


# Convert to DataFrame
df = pd.DataFrame(all_reviews, columns=['review', 'sentiment'])


# Shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Total reviews:", len(df))
print("Positive reviews:", len(df[df['sentiment']=='positive']))
print("Negative reviews:", len(df[df['sentiment']=='negative']))

"""Display 10 sample positive and negative reviews to understand dataset distribution and content"""

# Show 5 positive reviews
print("Positive Reviews:\n")

pos_reviews = df[df['sentiment'] == 'positive'].head(5)

for i, row in pos_reviews.iterrows():
    print("Positive:", row['review'])
    print("------")


# Show 10 negative reviews
print("\nNegative Reviews:\n")
neg_reviews = df[df['sentiment'] == 'negative'].head(5)

for i, row in neg_reviews.iterrows():
    print("Negative:", row['review'])
    print("------")

"""Objective 2: Text Cleaning

2.1 Text Preprocessing

The dataset is preprocessed to improve data quality and model performance. This includes converting text to lowercase, removing punctuation and stopwords, and applying lemmatization to standardise words.

Generate a word cloud to visualise the most common words in the review dataset
"""

# Import required libraries
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Convert all reviews to lowercase and store in a new column
df['clean_review'] = df['review'].apply(lambda x: x.lower())

# Combine all cleaned reviews into one single text
text = " ".join(df['clean_review'])

# Create the word cloud from the text
wordcloud = WordCloud(background_color="white").generate(text)

# Display the word cloud
plt.imshow(wordcloud)
plt.axis("off")   # Hide axis for better view
plt.show()

"""2.2 Check Review Length

This step checks the number of words in each review. Very short reviews may not provide enough information for sentiment analysis, so they are checked as possible outliers.
"""

# Count the number of words in each review
df['N_words'] = df['review'].apply(lambda x: len(x.split()))

# Display basic word count statistics
print("Mean words:", df['N_words'].mean())
print("Minimum words:", df['N_words'].min())
print("Maximum words:", df['N_words'].max())

# Check reviews with fewer than 3 words
df[df['N_words'] < 3]

"""2.3 Check Sentiment Balance

This step checks how many positive and negative reviews are in the dataset. A balanced dataset helps the model learn both sentiment classes fairly.
"""

# Count positive and negative reviews
sentiment_count = df['sentiment'].value_counts()

# Display sentiment count
print(sentiment_count)

"""2.4 Text Cleaning

The review text is cleaned to improve data quality and make it suitable for machine learning. This includes converting text to lowercase, removing punctuation and stopwords, and applying lemmatization to standardise words.
"""

# ===============================
# TEXT CLEANING
# ===============================

# Create tools for cleaning
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# Function to clean review text
def clean_text(text):

    # Convert text to lowercase
    text = text.lower()

    # Remove punctuation (e.g., ., !, ?)
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Split text into words
    words = text.split()

    # Remove stopwords and apply lemmatization
    cleaned_words = []
    for word in words:
        if word not in stop_words:           # remove stopwords
            word = lemmatizer.lemmatize(word)  # apply lemmatization
            cleaned_words.append(word)

    # Join cleaned words back into a sentence
    return " ".join(cleaned_words)

# Apply cleaning function to all reviews
df['clean_review'] = df['review'].apply(clean_text)

# Show original vs cleaned reviews
df[['review', 'clean_review']].head()

"""3.1 Feature Extraction

The cleaned review text is converted into numerical features using TF-IDF. This allows the machine learning model to process textual data by representing each review as a vector of word importance.
"""

# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),   # bigrams
    min_df=2
)

# Apply to cleaned text
X = vectorizer.fit_transform(df['clean_review'])

# Labels
y = df['sentiment']
print(vectorizer.get_feature_names_out()[:10])

"""3.2 Data Splitting

The dataset is split into training and testing sets to evaluate the model performance on unseen data.
"""

# Split again (VERY IMPORTANT)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train again
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict again
y_pred = model.predict(X_test)

# Check accuracy
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

"""4. Data Modelling

4.1 Model Training

The Logistic Regression model is used to classify the sentiment of reviews into positive and negative categories. The model is trained using the TF-IDF features from the cleaned dataset.
"""

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

"""4.2 Model Prediction

The model performance is evaluated using classification metrics such as accuracy, precision, recall, and F1-score.
"""

# ===============================
# NAIVE BAYES MODEL
# ===============================

from sklearn.naive_bayes import MultinomialNB

# Create model
nb_model = MultinomialNB()

# Train model
nb_model.fit(X_train, y_train)

print("Naive Bayes model trained")

"""4.3 Confusion Matrix

The confusion matrix is used to visualise the model performance by showing correct and incorrect predictions.
"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
sns.heatmap(confusion_matrix(y_test, y_pred),
            annot=True, fmt='d', cmap='Blues')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""4.3.1 Confusion Matrix Interpretation

The confusion matrix shows the performance of the model on the test dataset:

157 reviews were correctly predicted as positive (True Positive)

151 reviews were correctly predicted as negative (True Negative)

40 reviews were incorrectly predicted as negative (False Negative)

52 reviews were incorrectly predicted as positive (False Positive)
"""

from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

"""4.3.2 Model Accuracy

The model achieved an accuracy of 77% (or your value), which indicates how well the model correctly classifies positive and negative reviews.
"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", round(accuracy*100, 2), "%")

"""5. Model Testing with New Input"""

sample = ["This product is terrible, bad quality and waste of money"]

sample_clean = [clean_text(sample[0])]
sample_vector = vectorizer.transform(sample_clean)

prediction = model.predict(sample_vector)

print("Prediction:", prediction[0])

"""6. Neural Network Model

A neural network model is developed to further improve sentiment classification performance. The model uses TF-IDF features as input and applies dense layers to learn patterns from the review data.
"""

# ===============================
# NEURAL NETWORK MODEL
# ===============================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import LabelEncoder

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df['sentiment'])

# Split again
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# Convert to array (required for neural network)
X_train_nn = X_train.toarray()
X_test_nn = X_test.toarray()

# Build model
nn_model = Sequential()
nn_model.add(Dense(128, activation='relu', input_shape=(X_train_nn.shape[1],)))
nn_model.add(Dropout(0.3))
nn_model.add(Dense(64, activation='relu'))
nn_model.add(Dense(1, activation='sigmoid'))

# Compile
nn_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train
nn_model.fit(X_train_nn, y_train, epochs=5, batch_size=32)

# Evaluate
loss, accuracy = nn_model.evaluate(X_test_nn, y_test)

print("Neural Network Accuracy:", round(accuracy*100, 2), "%")

import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)